### ISSUE TITLE
Small problems

### ISSUE THREAD

**Issue by s0600204** [0ADMods/aristeia#6]
As you may be aware, I've been building a struct-tree visualisation for 0ad. Whilst linking Aristeia in so users can see what changes the mod makes, I came across a few... problems that I thought I'd bring to your attention.

~~Firstly, why are there two assyrian civs (`assy` and `assyrian`)? One of them is marked as selectable in game setup, the other is not. The reason I mention it is that the version that *is* selectable (``assy``) has just the one `StartEntity`: `units/assy_infantry_spearman_b`, and that unit doesn't exist! (The nearest appropriate unit appears to be `units/assyrian_infantry_spearman`). May I suggest the removal of the `assy` file in favour of the `assyrian`? (Although the `StartEntities` of this file will also need looking at.)~~

I'm not too sure what you're doing with the blacksmith, and trying to build structures from structures... still, both `units/egyptian_axe` and its promotion `units/egyptian_axe_a` are in the production/entities list of the egyptian blacksmith - may I ask why?

As you've decided to drop the `_b` suffix from basic units, you will need to add the following tokens to the production/entities list of both `structures/egyptian_large_temple` & `structures/egyptian_temple` (although the large temple is missing only the former):
* `-units/{civ}_support_healer_b`
* `units/egyptian_support_healer`

The linked icons of the following templates don't seem to exist:
* `structures/egyptian_small_wall_gate`
  * Current: `structural/wooden_gate.png`
  * Possible: `structures/wooden_gate.png`
* `units/egyptian_axe`
  * Current: `units/egyptian_infantry_axeman_256x256.png`
  * Possible: `units/egyptian_infantry_axeman_b_256x256.png`
* `units/egyptian_champion_infantry_royal_guard`
  * Current: `units/egyptian_infantry_axeman_2.png`
  * I'm guessing this icon hasn't been made yet?
* `units/egyptian_champion_infantry_swordsman`
  * Current: `units/egyptian_infantry_axeman_256x256.png`
  * Possible: `units/egyptian_infantry_swordsman_2.png`
* `units/egyptian_infantry_axeman`
  * Current: `units/egyptian_infantry_axeman_256x256.png`
  * Possible: `units/egyptian_infantry_axeman_b_256x256.png`
* `units/egyptian_priest`
  * Current: `units/assyrian_priest.png`
  * Possible: `units/egyptian_support_priest.png`
 
Talking of `units/egyptian_priest`, the civ code for that unit probably should be `egyptian`, no?

And finally, `units/egyptian_cavalry_javelinist_a` currently promotes to itself, rather than its elite form `units/egyptian_cavalry_javelinist_e`.

See: s0600204@777fc30713

**Comment by s0600204** [comment]
All resolved one way or another in recent changes.

**Comment by faerietree** [comment]
Thanks for pointing out the valid problems ... and fixing. You are the right councillor for this. I've not even realized all the encouraging activity (forks, fixes, proposals, ..) of you until now. 

Fixing these for 0AD unfortunately was out of my power as the Bronze Age extension to 0BC has severly diverged half a year ago. It has lost all compatibility to 0AD (e.g. in 0AD weapons and other features like the multiple inheritance or stackable structures aren't possible but are used in 0BC.BronzeAge).

I admit though that it's a maintenance nightmare ... not only because the 0AD developers and modders are skilled coders ... also because too much has been changed at once, at least the PyPy transition hasn't happened yet and that SpiderMonkey may even have surpassed V8 in performance (also thanks to asm.js it seems), makes this unnecessary for the foreseeing future.

In any regard, your work is appreciated. Thanks for tidying up what I left in a rush, for getting Aristeia usable in 0AD again.
